'use strict';

let fedExTrucks = '';

let inUse = [
  {
    unit: 975622,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 1,
    workArea: 'WA-101',
    status: 'IN SERVICE',
    parkingSpot: '1-2',
  },
  {
    unit: 975656,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 14,
    workArea: 'WA-102',
    status: 'IN SERVICE',
    parkingSpot: '2-1',
  },
  {
    unit: 975630,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 2,
    workArea: 'WA-105',
    status: 'IN SERVICE',
    parkingSpot: '1-2',
  },
  {
    unit: 975626,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 15,
    workArea: 'WA-106',
    status: 'IN SERVICE',
    parkingSpot: '2-2',
  },
  {
    unit: 975649,
    licensePlate: 'CA-19066',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 3,
    workArea: 'WA-109',
    status: 'IN SERVICE',
    parkingSpot: '1-3',
  },
  {
    unit: 975617,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 16,
    workArea: 'WA-110',
    status: 'IN SERVICE',
    parkingSpot: '2-3',
  },
  {
    unit: 975651,
    licensePlate: 'CA-19068',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 4,
    workArea: 'WA-113',
    status: 'IN SERVICE',
    parkingSpot: '1-4',
  },
  {
    unit: 977852,
    licensePlate: 'CA-67192',
    make: '',
    model: '1000',
    keySlot: 14,
    workArea: 'WA-114',
    status: 'IN SERVICE',
    parkingSpot: '2-4',
  },
  {
    unit: 975650,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 5,
    workArea: 'WA-117',
    status: 'IN SERVICE',
    parkingSpot: '1-5',
  },
  {
    unit: 975656,
    licensePlate: 'CA-',
    make: '',
    model: '1000',
    keySlot: 15,
    workArea: 'WA-118',
    status: 'IN SERVICE',
    parkingSpot: '2-5',
  },
  {
    unit: 975632,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 6,
    workArea: 'WA-121',
    status: 'IN SERVICE',
    parkingSpot: '1-6',
  },
  {
    unit: 975631,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 16,
    workArea: 'WA-122',
    status: 'IN SERVICE',
    parkingSpot: '2-6',
  },
  {
    unit: 975618,
    licensePlate: 'CA-13829',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 7,
    workArea: 'WA-125',
    status: 'IN SERVICE',
    parkingSpot: '1-7',
  },
  {
    unit: 975654,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 17,
    workArea: 'WA-126',
    status: 'IN SERVICE',
    parkingSpot: '2-7',
  },
  {
    unit: 975642,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 8,
    workArea: 'WA-129',
    status: 'IN SERVICE',
    parkingSpot: '1-8',
  },
  {
    unit: 975616,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 18,
    workArea: 'WA-130',
    status: 'IN SERVICE',
    parkingSpot: '2-8',
  },
  {
    unit: 975652,
    licensePlate: 'CA-13829',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 9,
    workArea: 'WA-133',
    status: 'IN SERVICE',
    parkingSpot: '1-9',
  },
  {
    unit: 975633,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 19,
    workArea: 'WA-134',
    status: 'IN SERVICE',
    parkingSpot: '2-9',
  },
  {
    unit: 975635,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 10,
    workArea: 'WA-137',
    status: 'IN SERVICE',
    parkingSpot: '1-10',
  },
  {
    unit: 975646,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 11,
    workArea: 'WA-141',
    status: 'IN SERVICE',
    parkingSpot: '1-11',
  },
  {
    unit: 975638,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 12,
    workArea: 'WA-145',
    status: 'IN SERVICE',
    parkingSpot: '1-12',
  },
  {
    unit: 975623,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 20,
    workArea: 'WA-201',
    status: 'IN SERVICE',
    parkingSpot: '1-13',
  },
  {
    unit: 975643,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 31,
    workArea: 'WA-202',
    status: 'IN SERVICE',
    parkingSpot: '2-13',
  },
  {
    unit: 970707,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 21,
    workArea: 'WA-205',
    status: 'IN SERVICE',
    parkingSpot: '1-14',
  },
  {
    unit: 977153,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 32,
    workArea: 'WA-206',
    status: 'IN SERVICE',
    parkingSpot: '2-14',
  },
  {
    unit: 975624,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 25,
    workArea: 'WA-209',
    status: 'IN SERVICE',
    parkingSpot: '1-15',
  },
  {
    unit: 970926,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 33,
    workArea: 'WA-210',
    status: 'IN SERVICE',
    parkingSpot: '2-15',
  },
  {
    unit: 975636,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 26,
    workArea: 'WA-213',
    status: 'IN SERVICE',
    parkingSpot: '1-16',
  },
  {
    unit: 975653,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 34,
    workArea: 'WA-214',
    status: 'IN SERVICE',
    parkingSpot: '2-16',
  },
  {
    unit: 970878,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 27,
    workArea: 'WA-217',
    status: 'IN SERVICE',
    parkingSpot: '1-17',
  },
  {
    unit: 975653,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 35,
    workArea: 'WA-218',
    status: 'IN SERVICE',
    parkingSpot: '2-17',
  },
  {
    unit: 975627,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 28,
    workArea: 'WA-221',
    status: 'IN SERVICE',
    parkingSpot: '1-18',
  },
  {
    unit: 977863,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 36,
    workArea: 'WA-222',
    status: 'IN SERVICE',
    parkingSpot: '2-18',
  },
  {
    unit: 977361,
    licensePlate: 'CB-66804',
    make: 'GMC',
    model: 'FedEx Ground',
    keySlot: 29,
    workArea: 'WA-225',
    status: 'IN SERVICE',
    parkingSpot: '1-19',
  },
  {
    unit: 975539,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 37,
    workArea: 'WA-226',
    status: 'IN SERVICE',
    parkingSpot: '2-19',
  },
  {
    unit: 975628,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 30,
    workArea: 'WA-229',
    status: 'IN SERVICE',
    parkingSpot: '1-20',
  },
  {
    unit: 975629,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 38,
    workArea: 'WA-230',
    status: 'IN SERVICE',
    parkingSpot: '2-20',
  },
  {
    unit: 975607,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 31,
    workArea: 'WA-233',
    status: 'IN SERVICE',
    parkingSpot: '1-21',
  },
  {
    unit: 975625,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 39,
    workArea: 'WA-234',
    status: 'IN SERVICE',
    parkingSpot: '2-21',
  },
  {
    unit: 975522,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 32,
    workArea: 'WA-237',
    status: 'IN SERVICE',
    parkingSpot: '1-22',
  },
  {
    unit: 5064382,
    licensePlate: 'CA-',
    make: '',
    model: '',
    keySlot: 40,
    workArea: 'WA-238',
    status: 'IN SERVICE',
    parkingSpot: '2-22',
  },
  {
    unit: 975644,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 33,
    workArea: 'WA-241',
    status: 'IN SERVICE',
    parkingSpot: '1-23',
  },
  {
    unit: 975520,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 41,
    workArea: 'WA-242',
    status: 'IN SERVICE',
    parkingSpot: '2-23',
  },
  {
    unit: 977853,
    licensePlate: 'CA-',
    make: 'GMC',
    model: 'CUBE',
    keySlot: 34,
    workArea: 'WA-245',
    status: 'IN SERVICE',
    parkingSpot: '2-24',
  },
  {
    unit: 975514,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 42,
    workArea: 'WA-246',
    status: 'IN SERVICE',
    parkingSpot: '2-24',
  },
  {
    unit: 976631,
    licensePlate: 'CA-19075',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 103,
    workArea: 'WA-250',
    status: 'IN SERVICE',
    parkingSpot: '',
  },
  {
    unit: 972907,
    licensePlate: 'AL-99294',
    make: 'FREIGHTLINER',
    model: '900',
    keySlot: '',
    workArea: 'WA-254',
    status: 'IN SERVICE',
    parkingSpot: '',
  },
  {
    unit: 975634,
    licensePlate: 'CA-19027',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: '',
    workArea: 'WA-258',
    status: 'IN SERVICE',
    parkingSpot: '',
  },
];

let spares = [
  {
    unit: 977156,
    licensePlate: 'CA-51459',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: '',
    workArea: '',
    status: 'IN SERVICE',
    parkingSpot: 'NORTH FENCE',
  },
  {
    unit: 977162,
    licensePlate: 'CB-64458',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 143,
    workArea: '',
    status: 'IN SERVICE',
    parkingSpot: 'NORTH FENCE',
  },
  {
    unit: 970877,
    licensePlate: '648-8RM',
    make: 'FREIGHTLINER',
    model: '700',
    keySlot: '',
    workArea: '',
    status: 'IN SERVICE',
    parkingSpot: '',
  },
  {
    unit: 977854,
    licensePlate: 'CB-67193',
    make: 'GMC',
    model: 'CUBE FEDEX GROUND',
    keySlot: 93,
    workArea: '',
    status: 'IN SERVICE',
    parkingSpot: '',
  },
  {
    unit: 975656,
    licensePlate: 'CA-',
    make: 'FREIGHTLINER',
    model: '1000',
    keySlot: 14,
    workArea: 'WA-102',
    status: 'IN SERVICE',
    parkingSpot: '2-1',
  },
];

console.log(inUse);

const workAreaId = {};
for (const value of inUse) {
  value.workArea = value.workArea.toLowerCase().replace('-', '');
  workAreaId[value.workArea] = value.unit;
}

console.log(workAreaId);

for (const value of inUse) {
  const input = document.getElementById(value.workArea);
  if (input) {
    input.placeholder = value.unit;
  }
}

workAreaId.wa102 = 977656;

console.log(workAreaId.wa102);

const workAreas = inUse.map(obj => obj.workArea);
console.log(workAreas);
const units = inUse.map(obj => obj.unit);
console.log(units);
const plates = inUse.map(obj => obj.licensePlate);
console.log(plates);

const searchInputValues = [...workAreas, ...units, ...plates];
console.log(searchInputValues);

document.querySelector('.enter').addEventListener('click', function (e) {
  console.log(document.querySelector());
});

// for (const search of workAreas) {
//   console.log(search);
// }

// for (const search of units) {
//   console.log(search);
// }

// for (const search of plates) {
//   console.log(search);
// }
